# Generated by Django 5.1.1 on 2024-10-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamrojob', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='salary_max',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='job',
            name='salary_min',
        ),
    ]
