# Generated by Django 5.1.1 on 2024-10-21 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamrojob', '0002_rename_salary_max_job_salary_remove_job_salary_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FullTime', 'Full Time'), ('PartTime', 'Part Time'), ('FreeLance', 'Freelance'), ('Internship', 'Internship'), ('Remote', 'Remote')], max_length=12),
        ),
    ]
