# Generated by Django 5.1.1 on 2024-10-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamrojob', '0003_alter_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('FreeLance', 'Freelance'), ('Internship', 'Internship'), ('Remote', 'Remote')], max_length=12),
        ),
    ]
