# Generated by Django 5.1.1 on 2024-10-24 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamrojob', '0004_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
    ]
