# Generated by Django 5.1.1 on 2024-11-18 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hamrojob', '0005_viewedjobs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewedJobs',
        ),
    ]
