# Generated by Django 5.1.1 on 2024-11-13 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='upload_resume',
            field=models.FileField(null=True, upload_to='resume'),
        ),
    ]
